<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * @var list<array<string, mixed>>
     */
    private const PRODUCTS = [
        [
            'slug' => 'nike-air-max-90',
            'name' => 'Nike Air Max 90',
            'sku' => 'PX-NKE-AM90',
            'brand' => 'Nike',
            'gender' => 'men',
            'color' => 'White',
            'category' => 'sneakers',
            'price' => 12999,
            'stock' => 24,
            'sizes' => [40, 41, 42, 43, 44, 45],
            'is_featured' => true,
            'image_url' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
            'description' => 'Classic Nike Air Max 90 with visible Air cushioning and durable rubber outsole.',
        ],
        [
            'slug' => 'adidas-ultraboost-22',
            'name' => 'Adidas Ultraboost 22',
            'sku' => 'PX-ADD-UB22',
            'brand' => 'Adidas',
            'gender' => 'unisex',
            'color' => 'Black',
            'category' => 'running',
            'price' => 17999,
            'stock' => 18,
            'sizes' => [38, 39, 40, 41, 42, 43, 44],
            'is_featured' => true,
            'image_url' => 'https://images.unsplash.com/photo-1606107557195-0be29b4b5b0b?w=800&q=80',
            'description' => 'Responsive Boost midsole and Primeknit upper for all-day comfort on the run.',
        ],
        [
            'slug' => 'new-balance-574',
            'name' => 'New Balance 574',
            'sku' => 'PX-NB-574',
            'brand' => 'New Balance',
            'gender' => 'unisex',
            'color' => 'Grey',
            'category' => 'casual',
            'price' => 9999,
            'stock' => 30,
            'sizes' => [38, 39, 40, 41, 42, 43, 44, 45],
            'is_featured' => true,
            'image_url' => 'https://images.unsplash.com/photo-1608231388042-1630b4e282a9?w=800&q=80',
            'description' => 'Heritage runner silhouette with ENCAP midsole support for everyday wear.',
        ],
        [
            'slug' => 'puma-rs-x',
            'name' => 'Puma RS-X',
            'sku' => 'PX-PM-RSX',
            'brand' => 'Puma',
            'gender' => 'men',
            'color' => 'Navy',
            'category' => 'sneakers',
            'price' => 10999,
            'compare_at_price' => 12999,
            'stock' => 15,
            'sizes' => [41, 42, 43, 44, 45],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
            'description' => 'Bold chunky design with RS running system cushioning.',
        ],
        [
            'slug' => 'timberland-6-inch-boot',
            'name' => 'Timberland 6-Inch Premium Boot',
            'sku' => 'PX-TMB-6IN',
            'brand' => 'Timberland',
            'gender' => 'men',
            'color' => 'Brown',
            'category' => 'boots',
            'price' => 19999,
            'stock' => 12,
            'sizes' => [41, 42, 43, 44, 45, 46],
            'is_featured' => true,
            'image_url' => 'https://images.unsplash.com/photo-1608256246330-53e6090a2b9a?w=800&q=80',
            'description' => 'Waterproof nubuck leather boot with padded collar and lug outsole.',
        ],
        [
            'slug' => 'dr-martens-1460',
            'name' => 'Dr. Martens 1460',
            'sku' => 'PX-DM-1460',
            'brand' => 'Dr. Martens',
            'gender' => 'unisex',
            'color' => 'Black',
            'category' => 'boots',
            'price' => 16999,
            'stock' => 20,
            'sizes' => [38, 39, 40, 41, 42, 43, 44],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80',
            'description' => 'Iconic 8-eye lace-up boot with AirWair bouncing soles.',
        ],
        [
            'slug' => 'birkenstock-arizona',
            'name' => 'Birkenstock Arizona',
            'sku' => 'PX-BRK-ARZ',
            'brand' => 'Birkenstock',
            'gender' => 'unisex',
            'color' => 'Brown',
            'category' => 'sandals',
            'price' => 8999,
            'stock' => 25,
            'sizes' => [38, 39, 40, 41, 42, 43, 44],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1603487742131-4160ec966093?w=800&q=80',
            'description' => 'Two-strap sandal with anatomically shaped cork-latex footbed.',
        ],
        [
            'slug' => 'nike-revolution-6',
            'name' => 'Nike Revolution 6',
            'sku' => 'PX-NKE-REV6',
            'brand' => 'Nike',
            'gender' => 'women',
            'color' => 'Pink',
            'category' => 'running',
            'price' => 6499,
            'stock' => 22,
            'sizes' => [36, 37, 38, 39, 40, 41],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1595341888016-a392ef81b1de?w=800&q=80',
            'description' => 'Lightweight everyday running shoe with soft foam midsole.',
        ],
        [
            'slug' => 'converse-chuck-70',
            'name' => 'Converse Chuck 70 High Top',
            'sku' => 'PX-CNV-CH70',
            'brand' => 'Converse',
            'gender' => 'unisex',
            'color' => 'White',
            'category' => 'casual',
            'price' => 8499,
            'stock' => 28,
            'sizes' => [38, 39, 40, 41, 42, 43, 44, 45],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8d077?w=800&q=80',
            'description' => 'Premium canvas high top with thicker sole and vintage details.',
        ],
        [
            'slug' => 'adidas-stan-smith',
            'name' => 'Adidas Stan Smith',
            'sku' => 'PX-ADD-STAN',
            'brand' => 'Adidas',
            'gender' => 'women',
            'color' => 'White',
            'category' => 'casual',
            'price' => 9499,
            'stock' => 19,
            'sizes' => [36, 37, 38, 39, 40, 41],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1560769629-975ec94d6a86?w=800&q=80',
            'description' => 'Minimal leather tennis shoe with perforated 3-Stripes.',
        ],
        [
            'slug' => 'nike-court-vision-low',
            'name' => 'Nike Court Vision Low',
            'sku' => 'PX-NKE-CVL',
            'brand' => 'Nike',
            'gender' => 'women',
            'color' => 'White',
            'category' => 'womens',
            'price' => 7499,
            'stock' => 16,
            'sizes' => [36, 37, 38, 39, 40],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1575549897834-49bbca7a7b60?w=800&q=80',
            'description' => 'Retro basketball-inspired low-top with classic cupsole.',
        ],
        [
            'slug' => 'nike-air-force-1',
            'name' => 'Nike Air Force 1',
            'sku' => 'PX-NKE-AF1',
            'brand' => 'Nike',
            'gender' => 'men',
            'color' => 'White',
            'category' => 'mens',
            'price' => 10999,
            'stock' => 21,
            'sizes' => [40, 41, 42, 43, 44, 45],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1600185365926-3a8ce9cbad2a?w=800&q=80',
            'description' => 'The basketball original with Nike Air cushioning in the heel.',
        ],
        [
            'slug' => 'adidas-superstar',
            'name' => 'Adidas Superstar',
            'sku' => 'PX-ADD-SSTAR',
            'brand' => 'Adidas',
            'gender' => 'kids',
            'color' => 'White',
            'category' => 'kids',
            'price' => 5999,
            'stock' => 14,
            'sizes' => [28, 29, 30, 31, 32, 33, 34, 35],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1514986888952-8c3203310bf4?w=800&q=80',
            'description' => 'Shell-toe classic scaled for kids with easy hook-and-loop strap.',
        ],
        [
            'slug' => 'nike-kids-revolution',
            'name' => 'Nike Kids Revolution 6',
            'sku' => 'PX-NKE-KREV',
            'brand' => 'Nike',
            'gender' => 'kids',
            'color' => 'Blue',
            'category' => 'kids',
            'price' => 4499,
            'stock' => 18,
            'sizes' => [28, 29, 30, 31, 32, 33, 34],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
            'description' => 'Flexible, breathable running shoe built for active kids.',
        ],
        [
            'slug' => 'reebok-classic-leather',
            'name' => 'Reebok Classic Leather',
            'sku' => 'PX-RBK-CL',
            'brand' => 'Reebok',
            'gender' => 'men',
            'color' => 'White',
            'category' => 'mens',
            'price' => 8999,
            'stock' => 17,
            'sizes' => [40, 41, 42, 43, 44],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1491553895911-9055-0816f4d6af4c?w=800&q=80',
            'description' => 'Soft garment leather upper with die-cut EVA midsole.',
        ],
        [
            'slug' => 'asics-gel-nimbus-25',
            'name' => 'ASICS Gel-Nimbus 25',
            'sku' => 'PX-ASC-GN25',
            'brand' => 'ASICS',
            'gender' => 'women',
            'color' => 'Purple',
            'category' => 'running',
            'price' => 15999,
            'stock' => 11,
            'sizes' => [37, 38, 39, 40, 41, 42],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800&q=80',
            'description' => 'Maximum cushioning with FF BLAST PLUS ECO foam and GEL technology.',
        ],
        [
            'slug' => 'vans-old-skool',
            'name' => 'Vans Old Skool',
            'sku' => 'PX-VNS-OS',
            'brand' => 'Vans',
            'gender' => 'unisex',
            'color' => 'Black',
            'category' => 'sneakers',
            'price' => 7499,
            'compare_at_price' => 8999,
            'stock' => 23,
            'sizes' => [38, 39, 40, 41, 42, 43, 44],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8d077?w=800&q=80',
            'description' => 'Original sidestripe skate shoe with durable canvas and suede upper.',
        ],
        [
            'slug' => 'clarks-desert-boot',
            'name' => 'Clarks Desert Boot',
            'sku' => 'PX-CLK-DSB',
            'brand' => 'Clarks',
            'gender' => 'men',
            'color' => 'Beige',
            'category' => 'boots',
            'price' => 12999,
            'stock' => 10,
            'sizes' => [41, 42, 43, 44, 45],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=800&q=80',
            'description' => 'Suede chukka boot with crepe sole — a timeless casual staple.',
        ],
        [
            'slug' => 'teva-universal-trail',
            'name' => 'Teva Universal Trail Sandal',
            'sku' => 'PX-TEV-UTS',
            'brand' => 'Teva',
            'gender' => 'women',
            'color' => 'Grey',
            'category' => 'sandals',
            'price' => 6999,
            'stock' => 13,
            'sizes' => [36, 37, 38, 39, 40, 41],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1603487742131-4160ec966093?w=800&q=80',
            'description' => 'Adjustable straps and rugged outsole for trail and water adventures.',
        ],
        [
            'slug' => 'new-balance-fresh-foam-x',
            'name' => 'New Balance Fresh Foam X 880v14',
            'sku' => 'PX-NB-880V14',
            'brand' => 'New Balance',
            'gender' => 'men',
            'color' => 'Blue',
            'category' => 'running',
            'price' => 13999,
            'stock' => 9,
            'sizes' => [41, 42, 43, 44, 45, 46],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1539185441755-769473a23569?w=800&q=80',
            'description' => 'Balanced cushioning for daily training with Fresh Foam X midsole.',
        ],
        [
            'slug' => 'skechers-go-walk-joy',
            'name' => 'Skechers Go Walk Joy',
            'sku' => 'PX-SKR-GWJ',
            'brand' => 'Skechers',
            'gender' => 'women',
            'color' => 'Black',
            'category' => 'womens',
            'price' => 5499,
            'stock' => 26,
            'sizes' => [36, 37, 38, 39, 40, 41],
            'is_featured' => false,
            'image_url' => 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&q=80',
            'description' => 'Ultra-light slip-on walking shoe with responsive cushioning.',
        ],
    ];

    public function run(): void
    {
        $categories = Category::query()->pluck('id', 'slug');

        foreach (self::PRODUCTS as $product) {
            $categorySlug = $product['category'];
            unset($product['category']);

            Product::query()->updateOrCreate(
                ['slug' => $product['slug']],
                [
                    ...$product,
                    'category_id' => $categories[$categorySlug],
                    'is_active' => true,
                ],
            );
        }
    }
}
